services:
  db:
    image: mysql/mysql-server
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    expose:
      - $MYSQLDB_LOCAL_PORT
    volumes:
      - art-of-bubble-tea-db:/var/lib/mysql
volumes:
  art-of-bubble-tea-db: