export interface DrinkData {
  name: string;
  bigToppings: string[];
  smallToppings: string[];
  milk: string[];
  sweetnessLevel: string[];
  iceLevel: string[];
  cupSize: string[];
}

export const CMF: DrinkData[] = [
  {
    name: "CMF Green Tea",
    bigToppings: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
    ],
    smallToppings: [
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: ["Soy milk", "Almond milk", "Lactose free milk"],
    sweetnessLevel: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    iceLevel: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    cupSize: ["Large", "Regular"],
  },
  {
    name: "CMF Black Tea",
    bigToppings: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
    ],
    smallToppings: [
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: ["Soy milk", "Almond milk", "Lactose free milk"],
    sweetnessLevel: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    iceLevel: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    cupSize: ["Large", "Regular"],
  },
  {
    name: "CMF Oolong Tea",
    bigToppings: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
    ],
    smallToppings: [
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: ["Soy milk", "Almond milk", "Lactose free milk"],
    sweetnessLevel: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    iceLevel: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    cupSize: ["Large", "Regular"],
  },
  {
    name: "CMF Rose",
    bigToppings: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
    ],
    smallToppings: [
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: ["Soy milk", "Almond milk", "Lactose free milk"],
    sweetnessLevel: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    iceLevel: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    cupSize: ["Large", "Regular"],
  },
  {
    name: "CMF Mango",
    bigToppings: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
    ],
    smallToppings: [
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: ["Soy milk", "Almond milk", "Lactose free milk"],
    sweetnessLevel: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    iceLevel: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    cupSize: ["Large", "Regular"],
  },
  {
    name: "CMF Chocolate",
    bigToppings: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
    ],
    smallToppings: [
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: ["Soy milk", "Almond milk", "Lactose free milk"],
    sweetnessLevel: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    iceLevel: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    cupSize: ["Large", "Regular"],
  },
  {
    name: "CMF Matcha",
    bigToppings: [
      "Brown sugar pearl",
      "Grass jelly",
      "Basil seeds",
      "Pudding",
      "Cheese milk foam",
      "Ice cream",
    ],
    smallToppings: [
      "Agar jelly",
      "Coco jelly",
      "Red bean",
      "Aloe vera",
      "Coffee jelly",
      "Agar bubble",
      "Strawberry popping boba",
      "Mango popping boba",
      "Lychee popping boba",
    ],
    milk: ["Soy milk", "Almond milk", "Lactose free milk"],
    sweetnessLevel: [
      "More (120%)",
      "Standard (100%)",
      "Less (70%)",
      "Half (50%)",
      "Little(30%)",
      "No sweet (0%)",
    ],
    iceLevel: ["Standard (100%)", "Less ice (30%)", "No ice (0%)"],
    cupSize: ["Large", "Regular"],
  },
];
